### ISSUE TITLE
Extract papers from ACL Anthology?

### ISSUE THREAD

**Issue by markusdr** [denkiwakame/arxiv2notion#13]
I'm a big fan of this project -- I might ditch the Mendeley reference manager for this. Are you planning to add more parsers?

It would be great to add a parser for the [ACL Anthology](https://aclanthology.org). It hosts almost 100k papers in natural language processing (NLP). 

Here is an example of the format: [https://aclanthology.org/2023.ijcnlp-main.1/](https://aclanthology.org/2023.ijcnlp-main.1/).

**Comment by denkiwakame** [comment]
Hi @markusdr ,

Thank you for your interest in this project and for your valuable suggestion. 
The idea of adding a parser for the ACL Anthology, considering its extensive collection of NLP papers, would be helpful for NLP researchers.

However, I'm currently hospitalized due to personal reasons and will be back next month, so I can't implement it immediately 😢 
If you need this feature right now, you can implement it similarly to the OpenReview parser ⬇️ 
https://github.com/denkiwakame/arxiv2notion/pull/11/files

Thank you once again for sharing your demands. I will be considering it in future release :)

**Comment by denkiwakame** [comment]
Hi @markusdr ,
i would like to inform you that I have finally added support for ACL Anthology. I have also reorganized the code to make it easier for other users to write their own parsers. 
https://github.com/denkiwakame/arxiv2notion/pull/16/files
This feature is available at v1.3.0.
https://github.com/denkiwakame/arxiv2notion/releases/tag/v1.3.0

The v1.3.0 release <s>will be available on the Chrome Store within the next few days</s> is now available on the  [Chrome Store](https://chrome.google.com/webstore/detail/jfgdgmjlakndggcpknmanlpgjgjbcbli) ✈️
