### ISSUE TITLE
"My Integrations" in notion redirected to another page

### ISSUE THREAD

**Issue by jubgjf** [denkiwakame/arxiv2notion#18]
Hi, the arxiv2notion plugin has been working very well for me. But not long ago, Notion seemed to update the Integrations system, and that breaks the plugin. I tried re-importing the Integration ID, but found that https://www.notion.so/my-integrations already pointed to https://www.notion.so/profile/integrations and I couldn't get the ID on this page.
<img width="1260" alt="截屏2024-07-16 下午1 01 01" src="https://github.com/user-attachments/assets/536985ec-1012-4911-8968-d1a7c2455dee">
<img width="1256" alt="截屏2024-07-16 下午1 01 33" src="https://github.com/user-attachments/assets/e098af42-d6e8-482f-8695-aee0b043e019">
What should I do to fix the plugin? Thank you.

**Comment by denkiwakame** [comment]
@jubgjf 

Thank you for reporting the issue . I hadn't noticed these updates. 😱
As a temporary solution, you can obtain your integration ID by visiting the following link and removing all "-" characters so that it becomes 32 characters long:
`https://www.notion.so/profile/integrations/internal/${your-integration-ID}`

For example, `https://www.notion.so/profile/integrations/internal/e1234567-1234-5678-1234-c35a3aa15d56` becomes `e1234567123456781234c35a3aa15d56`.

Then, paste the fixed ID and click the "+" button.
I have confirmed that this works and that the new integration ID (with the "-" characters removed) is the same as the previous version.
If this solution works for you, I will update the plugin to handle this issue so that users can simply copy and paste the integration ID from the URL.

<img src="https://private-user-images.githubusercontent.com/51768581/348946523-e098af42-d6e8-482f-8695-aee0b043e019.png" />

I don't clearly remember, but the old integration page used to display the integration ID without hyphens. The plugin would internally add the "-" characters to correct the integration ID and retrieve the secret ID from Notion. With the recent update, the true integration ID is now displayed with hyphens, which has caused a mismatch with the plugin's internal processing.

https://github.com/denkiwakame/arxiv2notion/blob/c5b8d7f40d05fc0d3ce3fea234534dea592773e3/src/js/options.js#L49-L54

**Comment by jubgjf** [comment]
Thanks! This solution works for me.

**Comment by denkiwakame** [comment]
@jubgjf Thank you for your report!
In [version 1.4.0](https://github.com/denkiwakame/arxiv2notion/releases/tag/v1.4.0), this issue has been fixed, and now you can simply copy and paste the new dashboard's integration ID (including hyphens) for the plugin to work. You can also install the latest version from the [Chrome Store](https://chromewebstore.google.com/detail/arxiv2notion/jfgdgmjlakndggcpknmanlpgjgjbcbli) .
